### ISSUE TITLE
Laggy website - use WGS84 for layers projection

### ISSUE THREAD

**Issue by marcovieiraruas** [EPFL-ENAC/alicelandings#18]
Hello, 

Website continues to be a tad laggy, to be tested if instead of using swiss coordinates projection for layers, using WGS84 works better, as it might be more suitable for folium.

**Comment by blueur** [comment]
Which layers seem to be slow ?
I'm not sure if changing the projection would help significantly... And it is not so easy to switch the projection ^^'

**Comment by charlottegiseleweil** [comment]
@blueur - I think you shoudl take care of this under the current agreement, as it's Phlebicite maintenance - so it's our responisability. If it becomes too time-consuming/new features we can charge this time to URBTREES indeed, as it will use the same underlying infra.

**Comment by guilbep** [comment]
@marcovieiraruas Hi, It will help us if you could tell us a bit more about 'how' it is laggy.
As @blueur said: Is a layer specifically slow ? I may add: What screen resolution/size are you using ? What browser ?
 
Do we have an agreement on speed already (@charlottegiseleweil) ?

Laggy is very much a 'feeling' and it's different for everyone.
 It's usually like this:
 - <0.3s it feels instantaneous
 - >0.3s & <1s It feels like it's working, but it's not instantaneous
 - >1s it's sluggish and we should inform the user that it's taking some time 
 
 What would be okay for you ?
 
 Could you do a screenvideo of it ? Maybe we could discuss that a bit more in a meeting.

**Comment by marcovieiraruas** [comment]
Hello,

Thank you for your answer.

 Latency is approximately 5 seconds (sluggish by your definition).

Chrome v. 106.0.5249.119.
Resolution : 1920x1200

I will email the video, it is too big to post here.

**Comment by marcovieiraruas** [comment]
Hello,

Any news on this?

**Comment by guilbep** [comment]
@marcovieiraruas we did not received any video concerning this.

**Comment by guilbep** [comment]
@marcovieiraruas here is a video, as you can see I don't experience any lag. 
In any case, if you don't provide the video, it'll be difficult to help. But we can investigate the following directions:
- What's your pc configuration (ram/cpu)
- What's your network speed ?
- What configuration of maps/layer do you use that you find 'laggy' ?

We need to identify what's laggy on your side, since we don't experience anything remotely close to the '5 second' lag your mentioning. @charlottegiseleweil do you have any input on this matter ?

here it is: https://filesender.switch.ch/filesender2/download.php?token=86ed5247-cf68-4950-83a6-2635dadf89d7&files_ids=307394

**Comment by charlottegiseleweil** [comment]
@marcovieiraruas please stop by our open space in person to show your perf issue to @guilbep or @blueur

**Comment by guilbep** [comment]
update by email directly to me: @marcovieiraruas it's better to avoid direct reply by email and to prefer github.

The video was sent on 9th december 2022. Pretty weird you did not receive it. 
So I had realized without video it would be difficult to help quite sometime ago actually.

In any case, herejoined is a video, and as you can see it I experience a pretty considerable lag. I also add an enacshare link if this does not get through : https://enacshare.epfl.ch/bg5QcM2Czm4a6eXpZohDS

 
What's your pc configuration (ram/cpu): 32 GB/ Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz   3.50 GHz
What's your network speed ?  EPFL network speed
What configuration of maps/layer do you use that you find 'laggy' ? Any combination of 3 + layers.

Thank you for your answer on github.

Herejoined the video. As mentionned in the comment latency is around 5 sec after action: ZOOM in and out. If multiple actions are performed at the same time also problematic: ZOOM and moving map by click and slide of the mouse. 

I used chrome but result probably similar on Firefox.

**Comment by guilbep** [comment]
Thank you @marcovieiraruas I'll have a look with @blueur as soon as possible

**Comment by blueur** [comment]
@marcovieiraruas
We think that the laggy behavior you described is mainly due to the layer size and number. 
In the Pierre's video, the reactivity seems acceptable because he only load a few number of layers each time. 
In yours, each time you change the zoom, all selected layers has to be reloaded.
We are sorry but we don't have a quick solution to technically improve that. Maybe you can send us some lighter layers and we can replace them ?
A possible solution would be to translate all layers to vector tiles, but it requires some big changes in the project...
